name: Run Anisette Server

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]  # Runs on push to main branch

jobs:
  run-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker container
        run: |
          docker build -t anisette-server .
          docker run -d -p 6969:6969 --name anisette anisette-server

      - name: Wait for server to start
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:6969 > /dev/null; do sleep 1; done'

      - name: Expose port
        uses: actions/github-script@v7
        with:
          script: |
            const port = 6969;
            const message = `🚀 Anisette server is running!\n\nConnect using:\nIP: ${{ github.server_url }}\nPort: ${port}\n\nNote: This server will be available until the workflow is cancelled.`;
            console.log(message); 